#!/usr/bin/env python3
"""Create a heuristic, read-only inventory of potentially user-visible text."""

from __future__ import annotations

import argparse
import fnmatch
import json
import re
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable


TEXT_EXTENSIONS = {
    ".astro", ".css", ".csv", ".htm", ".html", ".ini", ".java", ".js",
    ".json", ".jsx", ".kt", ".md", ".mdx", ".php", ".po", ".properties",
    ".py", ".rb", ".rst", ".svelte", ".toml", ".ts", ".tsx", ".txt",
    ".vue", ".xml", ".yaml", ".yml",
}
DEFAULT_EXCLUDED_DIRS = {
    ".git", ".hg", ".svn", ".next", ".nuxt", ".venv", "__pycache__",
    "build", "coverage", "dist", "node_modules", "target", "vendor",
}
USER_ATTRIBUTES = {"alt", "aria-label", "aria-description", "placeholder", "title"}
I18N_HINTS = {"i18n", "l10n", "locale", "locales", "messages", "translations"}
TEST_HINTS = {"fixture", "fixtures", "snapshot", "snapshots", "test", "tests", "__tests__"}
GENERATED_HINTS = {"generated", "autogenerated", "auto-generated", "do not edit"}


@dataclass(frozen=True)
class Candidate:
    path: str
    line: int
    text: str
    visibility: str
    confidence: str
    reason: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Heuristically inventory Polish/user-visible text without modifying files. "
            "Every search root must be supplied explicitly."
        )
    )
    parser.add_argument("paths", nargs="+", help="Files or directories to inspect")
    parser.add_argument(
        "--exclude", action="append", default=[], metavar="GLOB",
        help="Exclude a path matching this glob; repeatable",
    )
    parser.add_argument("--format", choices=("text", "json"), default="text")
    parser.add_argument("--output", help="Write the report to this file instead of stdout")
    parser.add_argument("--max-preview", type=int, default=240, help="Maximum preview length")
    return parser.parse_args()


def is_excluded(path: Path, patterns: list[str]) -> bool:
    if any(part.lower() in DEFAULT_EXCLUDED_DIRS for part in path.parts):
        return True
    normalized = path.as_posix()
    return any(fnmatch.fnmatch(normalized, pattern) or path.match(pattern) for pattern in patterns)


def iter_files(raw_paths: Iterable[str], patterns: list[str]) -> Iterable[Path]:
    seen: set[Path] = set()
    for raw in raw_paths:
        root = Path(raw).expanduser().resolve()
        if not root.exists():
            raise FileNotFoundError(f"Ścieżka nie istnieje: {root}")
        items = [root] if root.is_file() else root.rglob("*")
        for path in items:
            if not path.is_file() or is_excluded(path, patterns):
                continue
            if path.suffix.lower() not in TEXT_EXTENSIONS:
                continue
            resolved = path.resolve()
            if resolved not in seen:
                seen.add(resolved)
                yield resolved


def read_text(path: Path) -> str | None:
    data = path.read_bytes()
    if b"\x00" in data[:8192]:
        return None
    for encoding in ("utf-8-sig", "utf-8"):
        try:
            return data.decode(encoding)
        except UnicodeDecodeError:
            pass
    return None


def path_hints(path: Path) -> set[str]:
    return {part.lower() for part in path.parts}


def base_classification(path: Path, text: str) -> tuple[str, str, str] | None:
    hints = path_hints(path)
    lowered_head = text[:500].lower()
    if hints & TEST_HINTS:
        return ("NOT_USER_VISIBLE", "high", "ścieżka testu, fixture'a lub snapshotu")
    if hints & {"dist", "build"} or any(marker in lowered_head for marker in GENERATED_HINTS):
        return ("NOT_USER_VISIBLE", "high", "prawdopodobny artefakt generowany; znajdź źródło prawdy")
    return None


def clean_preview(value: str, limit: int) -> str:
    value = re.sub(r"\s+", " ", value).strip()
    return value if len(value) <= limit else value[: limit - 1] + "…"


def add_candidate(
    out: list[Candidate], path: Path, line: int, value: str,
    classification: tuple[str, str, str], limit: int,
) -> None:
    preview = clean_preview(value, limit)
    if not preview or preview in {"-", "*", "---", "..."}:
        return
    out.append(Candidate(str(path), line, preview, *classification))


def scan_markdown(path: Path, text: str, limit: int) -> list[Candidate]:
    out: list[Candidate] = []
    in_fence = False
    in_frontmatter = False
    for number, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if number == 1 and stripped == "---":
            in_frontmatter = True
            continue
        if in_frontmatter and stripped == "---":
            in_frontmatter = False
            continue
        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_fence = not in_fence
            continue
        if in_fence or in_frontmatter or stripped.startswith(("import ", "export ")):
            continue
        prose = re.sub(r"^#{1,6}\s+", "", stripped)
        prose = re.sub(r"^[-*+]\s+", "", prose)
        add_candidate(out, path, number, prose, ("CONFIRMED_VISIBLE", "high", "treść dokumentu Markdown/MDX"), limit)
    return out


def scan_markup(path: Path, text: str, limit: int) -> list[Candidate]:
    out: list[Candidate] = []
    for number, line in enumerate(text.splitlines(), 1):
        without_blocks = re.sub(r"<(script|style)\b[^>]*>.*?</\1>", "", line, flags=re.I)
        for match in re.finditer(r">\s*([^<{][^<]*)\s*<", without_blocks):
            add_candidate(out, path, number, match.group(1), ("CONFIRMED_VISIBLE", "high", "tekst węzła interfejsu"), limit)
        for match in re.finditer(r"\b(alt|aria-label|aria-description|placeholder|title)\s*=\s*([\"'])(.*?)\2", line, flags=re.I):
            if match.group(1).lower() in USER_ATTRIBUTES:
                add_candidate(out, path, number, match.group(3), ("CONFIRMED_VISIBLE", "high", f"atrybut użytkowy {match.group(1)}"), limit)
    return out


def walk_json(value: object, key_path: str = "$") -> Iterable[tuple[str, str]]:
    if isinstance(value, dict):
        for key, child in value.items():
            yield from walk_json(child, f"{key_path}.{key}")
    elif isinstance(value, list):
        for index, child in enumerate(value):
            yield from walk_json(child, f"{key_path}[{index}]")
    elif isinstance(value, str):
        yield key_path, value


def scan_json(path: Path, text: str, limit: int) -> list[Candidate]:
    out: list[Candidate] = []
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return scan_code(path, text, limit)
    hints = path_hints(path)
    classification = (
        ("LIKELY_VISIBLE", "medium", "wartość w prawdopodobnym zasobie i18n")
        if hints & I18N_HINTS
        else ("UNCERTAIN", "low", "wartość danych JSON; prześledź użycie")
    )
    for key_path, value in walk_json(data):
        line = text[: text.find(json.dumps(value, ensure_ascii=False))].count("\n") + 1 if value in text else 1
        add_candidate(out, path, line, f"{key_path}: {value}", classification, limit)
    return out


def scan_yaml_like(path: Path, text: str, limit: int) -> list[Candidate]:
    out: list[Candidate] = []
    hints = path_hints(path)
    classification = (
        ("LIKELY_VISIBLE", "medium", "wartość w prawdopodobnym zasobie i18n")
        if hints & I18N_HINTS
        else ("UNCERTAIN", "low", "wartość konfiguracji lub danych; prześledź użycie")
    )
    for number, line in enumerate(text.splitlines(), 1):
        match = re.match(r"^\s*[^#:\n]+:\s*[\"']?(.+?)[\"']?\s*$", line)
        if match:
            add_candidate(out, path, number, match.group(1), classification, limit)
    return out


def scan_po(path: Path, text: str, limit: int) -> list[Candidate]:
    out: list[Candidate] = []
    for number, line in enumerate(text.splitlines(), 1):
        match = re.match(r"\s*(msgid|msgstr(?:\[\d+\])?)\s+\"(.*)\"", line)
        if match and match.group(2):
            add_candidate(out, path, number, match.group(2), ("LIKELY_VISIBLE", "medium", f"wartość {match.group(1)} w katalogu PO"), limit)
    return out


STRING_RE = re.compile(r"(?<![\w])([\"'])([^\n\1]{2,}?)\1")


def scan_code(path: Path, text: str, limit: int) -> list[Candidate]:
    out = scan_markup(path, text, limit) if path.suffix.lower() in {".jsx", ".tsx", ".vue", ".svelte", ".astro"} else []
    hints = path_hints(path)
    for number, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if stripped.startswith(("//", "#", "/*", "*")):
            continue
        for match in STRING_RE.finditer(line):
            value = match.group(2)
            prefix = line[: match.start()].lower()
            if re.search(r"\b(import|require|from)\s*$", prefix) or value.startswith(("./", "../")):
                continue
            if re.search(r"\b(t|translate|gettext)\s*\(\s*$", prefix):
                classification = ("NOT_USER_VISIBLE", "medium", "prawdopodobny klucz lokalizacji, nie tekst")
            elif hints & I18N_HINTS:
                classification = ("LIKELY_VISIBLE", "medium", "literał w zasobie lokalizacyjnym")
            elif re.search(r"(message|label|title|description|placeholder|toast|alert|error)\s*[:=]\s*$", prefix):
                classification = ("LIKELY_VISIBLE", "medium", "literał przypisany do pola komunikatu lub interfejsu")
            else:
                classification = ("UNCERTAIN", "low", "literał w kodzie; prześledź ścieżkę wyświetlenia")
            add_candidate(out, path, number, value, classification, limit)
    return out


def scan_file(path: Path, text: str, limit: int) -> list[Candidate]:
    override = base_classification(path, text)
    suffix = path.suffix.lower()
    if suffix in {".md", ".mdx", ".rst", ".txt"}:
        found = scan_markdown(path, text, limit)
    elif suffix in {".html", ".htm", ".xml"}:
        found = scan_markup(path, text, limit)
    elif suffix == ".json":
        found = scan_json(path, text, limit)
    elif suffix in {".yaml", ".yml", ".toml", ".ini", ".properties"}:
        found = scan_yaml_like(path, text, limit)
    elif suffix == ".po":
        found = scan_po(path, text, limit)
    else:
        found = scan_code(path, text, limit)
    if override:
        return [Candidate(item.path, item.line, item.text, *override) for item in found]
    return found


def render_text(candidates: list[Candidate], scanned: int, skipped_binary: int) -> str:
    counts: dict[str, int] = {}
    for item in candidates:
        counts[item.visibility] = counts.get(item.visibility, 0) + 1
    lines = [
        "INWENTARZ HEURYSTYCZNY — wynik nie dowodzi widoczności w runtime",
        f"Pliki sprawdzone: {scanned}; binarne/nie-UTF-8 pominięte: {skipped_binary}; kandydaci: {len(candidates)}",
        "Klasy: " + ", ".join(f"{key}={value}" for key, value in sorted(counts.items())),
        "",
    ]
    for item in candidates:
        lines.append(f"[{item.visibility}/{item.confidence}] {item.path}:{item.line}")
        lines.append(f"  {item.text}")
        lines.append(f"  Powód: {item.reason}")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    args = parse_args()
    candidates: list[Candidate] = []
    scanned = 0
    skipped_binary = 0
    try:
        for path in iter_files(args.paths, args.exclude):
            text = read_text(path)
            if text is None:
                skipped_binary += 1
                continue
            scanned += 1
            candidates.extend(scan_file(path, text, args.max_preview))
    except (OSError, ValueError) as exc:
        print(f"BŁĄD: {exc}", file=sys.stderr)
        return 2

    candidates.sort(key=lambda item: (item.path.lower(), item.line, item.text))
    payload = {
        "notice": "Heurystyka inwentaryzacyjna; potwierdź ścieżkę użycia przed edycją.",
        "files_scanned": scanned,
        "binary_or_undecodable_skipped": skipped_binary,
        "candidates": [asdict(item) for item in candidates],
    }
    report = json.dumps(payload, ensure_ascii=False, indent=2) + "\n" if args.format == "json" else render_text(candidates, scanned, skipped_binary)
    if args.output:
        Path(args.output).resolve().write_text(report, encoding="utf-8")
    else:
        sys.stdout.write(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
